# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GestureRecognizer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GestureRecognizer
  pod 'MediaPipeTasksVision', '0.10.12'
  
  # Pods for SPICE
  pod 'TensorFlowLiteSwift', '~> 2.14.0', :subspecs => ['CoreML', 'Metal']
  pod 'TensorFlowLiteTaskAudio', '~> 0.4.3'
  pod 'TensorFlowLiteSelectTfOps', '~> 0.0.1-nightly'

end

target 'GestureRecognizerTests' do
  inherit! :search_paths
  # Pods for testing
end
